<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Guru extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Guru_model');
    } 

    /*
     * Listing of guru
     */
    function index()
    {
        $data['guru'] = $this->Guru_model->get_all_guru();
        
        $data['_view'] = 'guru/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new guru
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'contact' => $this->input->post('contact'),
				'address' => $this->input->post('address'),
            );
            
            $guru_id = $this->Guru_model->add_guru($params);
            redirect('main');
        }
        else
        {            
            $data['_view'] = 'guru/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a guru
     */
    function edit($id_pengajar)
    {   
        // check if the guru exists before trying to edit it
        $data['guru'] = $this->Guru_model->get_guru($id_pengajar);
        
        if(isset($data['guru']['id_pengajar']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'contact' => $this->input->post('contact'),
					'address' => $this->input->post('address'),
                );

                $this->Guru_model->update_guru($id_pengajar,$params);            
                redirect('main');
            }
            else
            {
                $data['_view'] = 'guru/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The guru you are trying to edit does not exist.');
    } 

    /*
     * Deleting guru
     */
    function remove($id_pengajar)
    {
        $guru = $this->Guru_model->get_guru($id_pengajar);

        // check if the guru exists before trying to delete it
        if(isset($guru['id_pengajar']))
        {
            $this->Guru_model->delete_guru($id_pengajar);
            redirect('main');
        }
        else
            show_error('The guru you are trying to delete does not exist.');
    }
    
}
